AllCops:
  Exclude:
    - "Gemfile"
    - "Guardfile"
    - "spec/spec_helper.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/LineLength:
  Max: 120

Security/Eval:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false
